version = 0.1

[default.deploy.parameters]
stack_name = "UserApi"
resolve_s3 = true
s3_prefix = "UserApi"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true

[default.global.parameters]
region = "ap-south-1"
